/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice;

import com.microsoft.rest.RestClient;

/**
 * The interface for MicrosoftScanningClient class.
 */
public interface MicrosoftScanningClient {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://";

    /**
     * Gets The Account Id.
     *
     * @return the accountName value.
     */
    String accountName();

    /**
     * Sets The Account Id.
     *
     * @param accountName the accountName value.
     * @return the service client itself
     */
    MicrosoftScanningClient withAccountName(String accountName);

    /**
     * Gets The Account Id.
     *
     * @return the accountId value.
     */
    String accountId();

    /**
     * Sets The Account Id.
     *
     * @param accountId the accountId value.
     * @return the service client itself
     */
    MicrosoftScanningClient withAccountId(String accountId);

    /**
     * Gets The api version to use..
     *
     * @return the apiVersion value.
     */
    String apiVersion();

    /**
     * Sets The api version to use..
     *
     * @param apiVersion the apiVersion value.
     * @return the service client itself
     */
    MicrosoftScanningClient withApiVersion(String apiVersion);

    /**
     * Gets the ClassificationRules object to access its operations.
     * @return the ClassificationRules object.
     */
    ClassificationRules classificationRules();

    /**
     * Gets the DataSources object to access its operations.
     * @return the DataSources object.
     */
    DataSources dataSources();

    /**
     * Gets the Filters object to access its operations.
     * @return the Filters object.
     */
    Filters filters();

    /**
     * Gets the Scans object to access its operations.
     * @return the Scans object.
     */
    Scans scans();

    /**
     * Gets the ScanRulesets object to access its operations.
     * @return the ScanRulesets object.
     */
    ScanRulesets scanRulesets();

    /**
     * Gets the Triggers object to access its operations.
     * @return the Triggers object.
     */
    Triggers triggers();

}
