// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataCatalogGen2.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AtlasClassifications
    /// </summary>
    /// <remarks>
    /// REST serialization friendly list.
    /// </remarks>
    public partial class JsonAtlasClassifications : JsonPList
    {
        /// <summary>
        /// Initializes a new instance of the JsonAtlasClassifications class.
        /// </summary>
        public JsonAtlasClassifications()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JsonAtlasClassifications class.
        /// </summary>
        /// <param name="list">An array of objects.</param>
        /// <param name="pageSize">The size of the page.</param>
        /// <param name="sortBy">The sorted by field.</param>
        /// <param name="sortType">Possible values include: 'NONE', 'ASC',
        /// 'DESC'</param>
        /// <param name="startIndex">The start index of the page.</param>
        /// <param name="totalCount">The total count of items.</param>
        public JsonAtlasClassifications(IList<object> list = default(IList<object>), int? pageSize = default(int?), string sortBy = default(string), string sortType = default(string), long? startIndex = default(long?), long? totalCount = default(long?))
            : base(list, pageSize, sortBy, sortType, startIndex, totalCount)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
