// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataCatalogGen2.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AtlasEntityExtInfo
    /// </summary>
    /// <remarks>
    /// An instance of an entity along with extended info - like hive_table,
    /// hive_database.
    /// </remarks>
    public partial class JsonAtlasEntityExtInfo
    {
        /// <summary>
        /// Initializes a new instance of the JsonAtlasEntityExtInfo class.
        /// </summary>
        public JsonAtlasEntityExtInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JsonAtlasEntityExtInfo class.
        /// </summary>
        /// <param name="referredEntities">The referred entities.</param>
        public JsonAtlasEntityExtInfo(IDictionary<string, JsonAtlasEntity> referredEntities = default(IDictionary<string, JsonAtlasEntity>))
        {
            ReferredEntities = referredEntities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the referred entities.
        /// </summary>
        [JsonProperty(PropertyName = "referredEntities")]
        public IDictionary<string, JsonAtlasEntity> ReferredEntities { get; set; }

    }
}
