// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataCatalogGen2.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AtlasTermAssignmentHeader
    /// </summary>
    /// <remarks>
    /// The header for term assignment.
    /// </remarks>
    public partial class JsonAtlasTermAssignmentHeader
    {
        /// <summary>
        /// Initializes a new instance of the JsonAtlasTermAssignmentHeader
        /// class.
        /// </summary>
        public JsonAtlasTermAssignmentHeader()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JsonAtlasTermAssignmentHeader
        /// class.
        /// </summary>
        /// <param name="confidence">The confidence of the term
        /// assignment.</param>
        /// <param name="createdBy">The user who created the record.</param>
        /// <param name="description">The description of the term
        /// assignment.</param>
        /// <param name="displayText">The display text.</param>
        /// <param name="expression">The expression of the term
        /// assignment.</param>
        /// <param name="relationGuid">The GUID of the relationship.</param>
        /// <param name="source">The source of the term.</param>
        /// <param name="status">Possible values include: 'DISCOVERED',
        /// 'PROPOSED', 'IMPORTED', 'VALIDATED', 'DEPRECATED', 'OBSOLETE',
        /// 'OTHER'</param>
        /// <param name="steward">The steward of the term.</param>
        /// <param name="termGuid">The GUID of the term.</param>
        public JsonAtlasTermAssignmentHeader(int? confidence = default(int?), string createdBy = default(string), string description = default(string), string displayText = default(string), string expression = default(string), string relationGuid = default(string), string source = default(string), string status = default(string), string steward = default(string), string termGuid = default(string))
        {
            Confidence = confidence;
            CreatedBy = createdBy;
            Description = description;
            DisplayText = displayText;
            Expression = expression;
            RelationGuid = relationGuid;
            Source = source;
            Status = status;
            Steward = steward;
            TermGuid = termGuid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the confidence of the term assignment.
        /// </summary>
        [JsonProperty(PropertyName = "confidence")]
        public int? Confidence { get; set; }

        /// <summary>
        /// Gets or sets the user who created the record.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Gets or sets the description of the term assignment.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the display text.
        /// </summary>
        [JsonProperty(PropertyName = "displayText")]
        public string DisplayText { get; set; }

        /// <summary>
        /// Gets or sets the expression of the term assignment.
        /// </summary>
        [JsonProperty(PropertyName = "expression")]
        public string Expression { get; set; }

        /// <summary>
        /// Gets or sets the GUID of the relationship.
        /// </summary>
        [JsonProperty(PropertyName = "relationGuid")]
        public string RelationGuid { get; set; }

        /// <summary>
        /// Gets or sets the source of the term.
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'DISCOVERED', 'PROPOSED',
        /// 'IMPORTED', 'VALIDATED', 'DEPRECATED', 'OBSOLETE', 'OTHER'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets the steward of the term.
        /// </summary>
        [JsonProperty(PropertyName = "steward")]
        public string Steward { get; set; }

        /// <summary>
        /// Gets or sets the GUID of the term.
        /// </summary>
        [JsonProperty(PropertyName = "termGuid")]
        public string TermGuid { get; set; }

    }
}
