// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataCatalogGen2.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SuggestResultValue
    /// </summary>
    /// <remarks>
    /// The value item of the search suggest.
    /// </remarks>
    public partial class JsonSuggestResultValue
    {
        /// <summary>
        /// Initializes a new instance of the JsonSuggestResultValue class.
        /// </summary>
        public JsonSuggestResultValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JsonSuggestResultValue class.
        /// </summary>
        /// <param name="searchtext">The target text that contains the keyword
        /// as prefix. The keyword is wrapped with emphasis mark.</param>
        /// <param name="description">The description of the record.</param>
        /// <param name="id">The ID of the record.</param>
        /// <param name="name">The name of the record.</param>
        /// <param name="owner">The owner of the record.</param>
        /// <param name="qualifiedName">The qualified name of the
        /// record.</param>
        /// <param name="typeName">The type name of the record.</param>
        public JsonSuggestResultValue(string searchtext = default(string), string description = default(string), string id = default(string), string name = default(string), string owner = default(string), string qualifiedName = default(string), string typeName = default(string))
        {
            Searchtext = searchtext;
            Description = description;
            Id = id;
            Name = name;
            Owner = owner;
            QualifiedName = qualifiedName;
            TypeName = typeName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the target text that contains the keyword as prefix.
        /// The keyword is wrapped with emphasis mark.
        /// </summary>
        [JsonProperty(PropertyName = "@search.text")]
        public string Searchtext { get; set; }

        /// <summary>
        /// Gets or sets the description of the record.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the ID of the record.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the record.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the owner of the record.
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string Owner { get; set; }

        /// <summary>
        /// Gets or sets the qualified name of the record.
        /// </summary>
        [JsonProperty(PropertyName = "qualifiedName")]
        public string QualifiedName { get; set; }

        /// <summary>
        /// Gets or sets the type name of the record.
        /// </summary>
        [JsonProperty(PropertyName = "typeName")]
        public string TypeName { get; set; }

    }
}
