/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice.implementation;

import java.util.List;
import com.msft.atlasscanservice.JsonSearchResultValue;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AdvancedResult.
 * The result item of the search suggest.
 */
public class JsonAdvancedResultInner {
    /**
     * The total number of search results (not the number of documents in a
     * single page).
     */
    @JsonProperty(value = "@search\\.count")
    private Integer searchcount;

    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private List<JsonSearchResultValue> value;

    /**
     * Get the total number of search results (not the number of documents in a single page).
     *
     * @return the searchcount value
     */
    public Integer searchcount() {
        return this.searchcount;
    }

    /**
     * Set the total number of search results (not the number of documents in a single page).
     *
     * @param searchcount the searchcount value to set
     * @return the JsonAdvancedResultInner object itself.
     */
    public JsonAdvancedResultInner withSearchcount(Integer searchcount) {
        this.searchcount = searchcount;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<JsonSearchResultValue> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the JsonAdvancedResultInner object itself.
     */
    public JsonAdvancedResultInner withValue(List<JsonSearchResultValue> value) {
        this.value = value;
        return this;
    }

}
