/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice.implementation;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasTypeDefHeader.
 * The basic information of the type definition.
 */
public class JsonAtlasTypeDefHeaderInner {
    /**
     * Possible values include: 'PRIMITIVE', 'OBJECT_ID_TYPE', 'ENUM',
     * 'STRUCT', 'CLASSIFICATION', 'ENTITY', 'ARRAY', 'MAP', 'RELATIONSHIP'.
     */
    @JsonProperty(value = "category")
    private String category;

    /**
     * The GUID of the type definition.
     */
    @JsonProperty(value = "guid")
    private String guid;

    /**
     * The name of the type definition.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Get possible values include: 'PRIMITIVE', 'OBJECT_ID_TYPE', 'ENUM', 'STRUCT', 'CLASSIFICATION', 'ENTITY', 'ARRAY', 'MAP', 'RELATIONSHIP'.
     *
     * @return the category value
     */
    public String category() {
        return this.category;
    }

    /**
     * Set possible values include: 'PRIMITIVE', 'OBJECT_ID_TYPE', 'ENUM', 'STRUCT', 'CLASSIFICATION', 'ENTITY', 'ARRAY', 'MAP', 'RELATIONSHIP'.
     *
     * @param category the category value to set
     * @return the JsonAtlasTypeDefHeaderInner object itself.
     */
    public JsonAtlasTypeDefHeaderInner withCategory(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get the GUID of the type definition.
     *
     * @return the guid value
     */
    public String guid() {
        return this.guid;
    }

    /**
     * Set the GUID of the type definition.
     *
     * @param guid the guid value to set
     * @return the JsonAtlasTypeDefHeaderInner object itself.
     */
    public JsonAtlasTypeDefHeaderInner withGuid(String guid) {
        this.guid = guid;
        return this;
    }

    /**
     * Get the name of the type definition.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of the type definition.
     *
     * @param name the name value to set
     * @return the JsonAtlasTypeDefHeaderInner object itself.
     */
    public JsonAtlasTypeDefHeaderInner withName(String name) {
        this.name = name;
        return this;
    }

}
