/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice.implementation;

import com.msft.atlasscanservice.JsonAtlasEntity;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.msft.atlasscanservice.JsonAtlasEntityExtInfo;

/**
 * AtlasEntityWithExtInfo.
 * An instance of an entity along with extended info - like hive_table,
 * hive_database.
 */
public class JsonAtlasEntityWithExtInfoInner extends JsonAtlasEntityExtInfo {
    /**
     * The entity property.
     */
    @JsonProperty(value = "entity")
    private JsonAtlasEntity entity;

    /**
     * Get the entity value.
     *
     * @return the entity value
     */
    public JsonAtlasEntity entity() {
        return this.entity;
    }

    /**
     * Set the entity value.
     *
     * @param entity the entity value to set
     * @return the JsonAtlasEntityWithExtInfoInner object itself.
     */
    public JsonAtlasEntityWithExtInfoInner withEntity(JsonAtlasEntity entity) {
        this.entity = entity;
        return this;
    }

}
