/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice.implementation;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasEntityDef.
 * class that captures details of a entity-type.
 */
public class JsonAtlasEntityDefInner extends JsonAtlasStructDefInner {
    /**
     * An array of sub types.
     */
    @JsonProperty(value = "subTypes")
    private List<String> subTypes;

    /**
     * An array of super types.
     */
    @JsonProperty(value = "superTypes")
    private List<String> superTypes;

    /**
     * Get an array of sub types.
     *
     * @return the subTypes value
     */
    public List<String> subTypes() {
        return this.subTypes;
    }

    /**
     * Set an array of sub types.
     *
     * @param subTypes the subTypes value to set
     * @return the JsonAtlasEntityDefInner object itself.
     */
    public JsonAtlasEntityDefInner withSubTypes(List<String> subTypes) {
        this.subTypes = subTypes;
        return this;
    }

    /**
     * Get an array of super types.
     *
     * @return the superTypes value
     */
    public List<String> superTypes() {
        return this.superTypes;
    }

    /**
     * Set an array of super types.
     *
     * @param superTypes the superTypes value to set
     * @return the JsonAtlasEntityDefInner object itself.
     */
    public JsonAtlasEntityDefInner withSuperTypes(List<String> superTypes) {
        this.superTypes = superTypes;
        return this;
    }

}
