// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ScannerBabylonService
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// Creates a Microsoft.Scanning management client.
    /// </summary>
    public partial interface IMicrosoftScanningClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// The Account Id
        /// </summary>
        string AccountName { get; set; }

        /// <summary>
        /// The Account Id
        /// </summary>
        string AccountId { get; set; }

        /// <summary>
        /// The api version to use.
        /// </summary>
        string ApiVersion { get; set; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IClassificationRules.
        /// </summary>
        IClassificationRules ClassificationRules { get; }

        /// <summary>
        /// Gets the IDataSources.
        /// </summary>
        IDataSources DataSources { get; }

        /// <summary>
        /// Gets the IFilters.
        /// </summary>
        IFilters Filters { get; }

        /// <summary>
        /// Gets the IScans.
        /// </summary>
        IScans Scans { get; }

        /// <summary>
        /// Gets the IScanRulesets.
        /// </summary>
        IScanRulesets ScanRulesets { get; }

        /// <summary>
        /// Gets the ITriggers.
        /// </summary>
        ITriggers Triggers { get; }

    }
}
