// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataCatalogGen2.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AtlasGlossaryCategory
    /// </summary>
    /// <remarks>
    /// The glossary category.
    /// </remarks>
    public partial class JsonAtlasGlossaryCategory : JsonAtlasGlossaryBaseObject
    {
        /// <summary>
        /// Initializes a new instance of the JsonAtlasGlossaryCategory class.
        /// </summary>
        public JsonAtlasGlossaryCategory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JsonAtlasGlossaryCategory class.
        /// </summary>
        /// <param name="guid">The GUID of the object.</param>
        /// <param name="classifications">An array of classifications.</param>
        /// <param name="longDescription">The long version description.</param>
        /// <param name="name">The name of the glossary object.</param>
        /// <param name="qualifiedName">The qualified name of the glossary
        /// object.</param>
        /// <param name="shortDescription">The short version of
        /// description.</param>
        /// <param name="childrenCategories">An array of children
        /// categories.</param>
        /// <param name="terms">An array of related term headers.</param>
        public JsonAtlasGlossaryCategory(string guid = default(string), IList<JsonAtlasClassification> classifications = default(IList<JsonAtlasClassification>), string longDescription = default(string), string name = default(string), string qualifiedName = default(string), string shortDescription = default(string), JsonAtlasGlossaryHeader anchor = default(JsonAtlasGlossaryHeader), IList<JsonAtlasRelatedCategoryHeader> childrenCategories = default(IList<JsonAtlasRelatedCategoryHeader>), JsonAtlasRelatedCategoryHeader parentCategory = default(JsonAtlasRelatedCategoryHeader), IList<JsonAtlasRelatedTermHeader> terms = default(IList<JsonAtlasRelatedTermHeader>))
            : base(guid, classifications, longDescription, name, qualifiedName, shortDescription)
        {
            Anchor = anchor;
            ChildrenCategories = childrenCategories;
            ParentCategory = parentCategory;
            Terms = terms;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "anchor")]
        public JsonAtlasGlossaryHeader Anchor { get; set; }

        /// <summary>
        /// Gets or sets an array of children categories.
        /// </summary>
        [JsonProperty(PropertyName = "childrenCategories")]
        public IList<JsonAtlasRelatedCategoryHeader> ChildrenCategories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentCategory")]
        public JsonAtlasRelatedCategoryHeader ParentCategory { get; set; }

        /// <summary>
        /// Gets or sets an array of related term headers.
        /// </summary>
        [JsonProperty(PropertyName = "terms")]
        public IList<JsonAtlasRelatedTermHeader> Terms { get; set; }

    }
}
