// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ScannerBabylonService.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("AmazonS3")]
    [JsonTransformation]
    public partial class AmazonS3DataSource : DataSource
    {
        /// <summary>
        /// Initializes a new instance of the AmazonS3DataSource class.
        /// </summary>
        public AmazonS3DataSource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AmazonS3DataSource class.
        /// </summary>
        public AmazonS3DataSource(string id = default(string), string name = default(string), System.DateTime? createdAt = default(System.DateTime?), System.DateTime? lastModifiedAt = default(System.DateTime?), string serviceUrl = default(string), string roleARN = default(string))
            : base(id, name)
        {
            CreatedAt = createdAt;
            LastModifiedAt = lastModifiedAt;
            ServiceUrl = serviceUrl;
            RoleARN = roleARN;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties.createdAt")]
        public System.DateTime? CreatedAt { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties.lastModifiedAt")]
        public System.DateTime? LastModifiedAt { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties.serviceUrl")]
        public string ServiceUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties.roleARN")]
        public string RoleARN { get; set; }

    }
}
