/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.implementation;

import retrofit2.Retrofit;
import com.msft.babylonscanningservice.ScanRulesets;
import com.google.common.reflect.TypeToken;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import com.microsoft.rest.Validator;
import com.msft.babylonscanningservice.models.ErrorResponseModelException;
import com.msft.babylonscanningservice.models.ScanRuleset;
import com.msft.babylonscanningservice.models.ScanRulesetList;
import java.io.IOException;
import okhttp3.ResponseBody;
import retrofit2.Response;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.HTTP;
import retrofit2.http.Header;
import retrofit2.http.Headers;
import retrofit2.http.PUT;
import retrofit2.http.Path;
import retrofit2.http.Query;
import rx.Observable;
import rx.functions.Func1;

/**
 * An instance of this class provides access to all the operations defined
 * in ScanRulesets.
 */
public class ScanRulesetsImpl implements ScanRulesets {
    /** The Retrofit service to perform REST calls. */
    private ScanRulesetsService service;
    /** The service client containing this operation class. */
    private MicrosoftScanningClientImpl client;

    /**
     * Initializes an instance of ScanRulesets.
     *
     * @param retrofit the Retrofit instance built from a Retrofit Builder.
     * @param client the instance of the service client containing this operation class.
     */
    public ScanRulesetsImpl(Retrofit retrofit, MicrosoftScanningClientImpl client) {
        this.service = retrofit.create(ScanRulesetsService.class);
        this.client = client;
    }

    /**
     * The interface defining all the services for ScanRulesets to be
     * used by Retrofit to perform actually REST calls.
     */
    interface ScanRulesetsService {
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.msft.babylonscanningservice.ScanRulesets get" })
        @GET("scanrulesets/{scanRulesetName}")
        Observable<Response<ResponseBody>> get(@Path("scanRulesetName") String scanRulesetName, @Header("x-ms-account-id") String accountId, @Header("x-ms-account-name") String accountName, @Query("api-version") String apiVersion);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.msft.babylonscanningservice.ScanRulesets createOrUpdate" })
        @PUT("scanrulesets/{scanRulesetName}")
        Observable<Response<ResponseBody>> createOrUpdate(@Path("scanRulesetName") String scanRulesetName, @Header("x-ms-account-id") String accountId, @Header("x-ms-account-name") String accountName, @Query("api-version") String apiVersion, @Body ScanRuleset body);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.msft.babylonscanningservice.ScanRulesets delete" })
        @HTTP(path = "scanrulesets/{scanRulesetName}", method = "DELETE", hasBody = true)
        Observable<Response<ResponseBody>> delete(@Path("scanRulesetName") String scanRulesetName, @Header("x-ms-account-id") String accountId, @Header("x-ms-account-name") String accountName, @Query("api-version") String apiVersion);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.msft.babylonscanningservice.ScanRulesets listAll" })
        @GET("scanrulesets")
        Observable<Response<ResponseBody>> listAll(@Query("$skipToken") String skipToken, @Header("x-ms-account-id") String accountId, @Header("x-ms-account-name") String accountName, @Query("api-version") String apiVersion);

    }

    /**
     * Get a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseModelException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ScanRuleset object if successful.
     */
    public ScanRuleset get(String scanRulesetName) {
        return getWithServiceResponseAsync(scanRulesetName).toBlocking().single().body();
    }

    /**
     * Get a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ScanRuleset> getAsync(String scanRulesetName, final ServiceCallback<ScanRuleset> serviceCallback) {
        return ServiceFuture.fromResponse(getWithServiceResponseAsync(scanRulesetName), serviceCallback);
    }

    /**
     * Get a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRuleset object
     */
    public Observable<ScanRuleset> getAsync(String scanRulesetName) {
        return getWithServiceResponseAsync(scanRulesetName).map(new Func1<ServiceResponse<ScanRuleset>, ScanRuleset>() {
            @Override
            public ScanRuleset call(ServiceResponse<ScanRuleset> response) {
                return response.body();
            }
        });
    }

    /**
     * Get a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRuleset object
     */
    public Observable<ServiceResponse<ScanRuleset>> getWithServiceResponseAsync(String scanRulesetName) {
        if (scanRulesetName == null) {
            throw new IllegalArgumentException("Parameter scanRulesetName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        return service.get(scanRulesetName, this.client.accountId(), this.client.accountName(), this.client.apiVersion())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ScanRuleset>>>() {
                @Override
                public Observable<ServiceResponse<ScanRuleset>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ScanRuleset> clientResponse = getDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<ScanRuleset> getDelegate(Response<ResponseBody> response) throws ErrorResponseModelException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<ScanRuleset, ErrorResponseModelException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<ScanRuleset>() { }.getType())
                .registerError(ErrorResponseModelException.class)
                .build(response);
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseModelException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ScanRuleset object if successful.
     */
    public ScanRuleset createOrUpdate(String scanRulesetName) {
        return createOrUpdateWithServiceResponseAsync(scanRulesetName).toBlocking().single().body();
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ScanRuleset> createOrUpdateAsync(String scanRulesetName, final ServiceCallback<ScanRuleset> serviceCallback) {
        return ServiceFuture.fromResponse(createOrUpdateWithServiceResponseAsync(scanRulesetName), serviceCallback);
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRuleset object
     */
    public Observable<ScanRuleset> createOrUpdateAsync(String scanRulesetName) {
        return createOrUpdateWithServiceResponseAsync(scanRulesetName).map(new Func1<ServiceResponse<ScanRuleset>, ScanRuleset>() {
            @Override
            public ScanRuleset call(ServiceResponse<ScanRuleset> response) {
                return response.body();
            }
        });
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRuleset object
     */
    public Observable<ServiceResponse<ScanRuleset>> createOrUpdateWithServiceResponseAsync(String scanRulesetName) {
        if (scanRulesetName == null) {
            throw new IllegalArgumentException("Parameter scanRulesetName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        final ScanRuleset body = null;
        return service.createOrUpdate(scanRulesetName, this.client.accountId(), this.client.accountName(), this.client.apiVersion(), body)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ScanRuleset>>>() {
                @Override
                public Observable<ServiceResponse<ScanRuleset>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ScanRuleset> clientResponse = createOrUpdateDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param body the ScanRuleset value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseModelException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ScanRuleset object if successful.
     */
    public ScanRuleset createOrUpdate(String scanRulesetName, ScanRuleset body) {
        return createOrUpdateWithServiceResponseAsync(scanRulesetName, body).toBlocking().single().body();
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param body the ScanRuleset value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ScanRuleset> createOrUpdateAsync(String scanRulesetName, ScanRuleset body, final ServiceCallback<ScanRuleset> serviceCallback) {
        return ServiceFuture.fromResponse(createOrUpdateWithServiceResponseAsync(scanRulesetName, body), serviceCallback);
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param body the ScanRuleset value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRuleset object
     */
    public Observable<ScanRuleset> createOrUpdateAsync(String scanRulesetName, ScanRuleset body) {
        return createOrUpdateWithServiceResponseAsync(scanRulesetName, body).map(new Func1<ServiceResponse<ScanRuleset>, ScanRuleset>() {
            @Override
            public ScanRuleset call(ServiceResponse<ScanRuleset> response) {
                return response.body();
            }
        });
    }

    /**
     * Creates or Updates a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param body the ScanRuleset value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRuleset object
     */
    public Observable<ServiceResponse<ScanRuleset>> createOrUpdateWithServiceResponseAsync(String scanRulesetName, ScanRuleset body) {
        if (scanRulesetName == null) {
            throw new IllegalArgumentException("Parameter scanRulesetName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        Validator.validate(body);
        return service.createOrUpdate(scanRulesetName, this.client.accountId(), this.client.accountName(), this.client.apiVersion(), body)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ScanRuleset>>>() {
                @Override
                public Observable<ServiceResponse<ScanRuleset>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ScanRuleset> clientResponse = createOrUpdateDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<ScanRuleset> createOrUpdateDelegate(Response<ResponseBody> response) throws ErrorResponseModelException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<ScanRuleset, ErrorResponseModelException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<ScanRuleset>() { }.getType())
                .register(201, new TypeToken<ScanRuleset>() { }.getType())
                .registerError(ErrorResponseModelException.class)
                .build(response);
    }

    /**
     * Deletes a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseModelException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    public void delete(String scanRulesetName) {
        deleteWithServiceResponseAsync(scanRulesetName).toBlocking().single().body();
    }

    /**
     * Deletes a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<Void> deleteAsync(String scanRulesetName, final ServiceCallback<Void> serviceCallback) {
        return ServiceFuture.fromResponse(deleteWithServiceResponseAsync(scanRulesetName), serviceCallback);
    }

    /**
     * Deletes a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    public Observable<Void> deleteAsync(String scanRulesetName) {
        return deleteWithServiceResponseAsync(scanRulesetName).map(new Func1<ServiceResponse<Void>, Void>() {
            @Override
            public Void call(ServiceResponse<Void> response) {
                return response.body();
            }
        });
    }

    /**
     * Deletes a scan ruleset.
     *
     * @param scanRulesetName the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    public Observable<ServiceResponse<Void>> deleteWithServiceResponseAsync(String scanRulesetName) {
        if (scanRulesetName == null) {
            throw new IllegalArgumentException("Parameter scanRulesetName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        return service.delete(scanRulesetName, this.client.accountId(), this.client.accountName(), this.client.apiVersion())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Void>>>() {
                @Override
                public Observable<ServiceResponse<Void>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<Void> clientResponse = deleteDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<Void> deleteDelegate(Response<ResponseBody> response) throws ErrorResponseModelException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<Void, ErrorResponseModelException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<Void>() { }.getType())
                .register(202, new TypeToken<Void>() { }.getType())
                .register(204, new TypeToken<Void>() { }.getType())
                .registerError(ErrorResponseModelException.class)
                .build(response);
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseModelException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ScanRulesetList object if successful.
     */
    public ScanRulesetList listAll() {
        return listAllWithServiceResponseAsync().toBlocking().single().body();
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ScanRulesetList> listAllAsync(final ServiceCallback<ScanRulesetList> serviceCallback) {
        return ServiceFuture.fromResponse(listAllWithServiceResponseAsync(), serviceCallback);
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRulesetList object
     */
    public Observable<ScanRulesetList> listAllAsync() {
        return listAllWithServiceResponseAsync().map(new Func1<ServiceResponse<ScanRulesetList>, ScanRulesetList>() {
            @Override
            public ScanRulesetList call(ServiceResponse<ScanRulesetList> response) {
                return response.body();
            }
        });
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRulesetList object
     */
    public Observable<ServiceResponse<ScanRulesetList>> listAllWithServiceResponseAsync() {
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        final String skipToken = null;
        return service.listAll(skipToken, this.client.accountId(), this.client.accountName(), this.client.apiVersion())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ScanRulesetList>>>() {
                @Override
                public Observable<ServiceResponse<ScanRulesetList>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ScanRulesetList> clientResponse = listAllDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @param skipToken the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseModelException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ScanRulesetList object if successful.
     */
    public ScanRulesetList listAll(String skipToken) {
        return listAllWithServiceResponseAsync(skipToken).toBlocking().single().body();
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @param skipToken the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ScanRulesetList> listAllAsync(String skipToken, final ServiceCallback<ScanRulesetList> serviceCallback) {
        return ServiceFuture.fromResponse(listAllWithServiceResponseAsync(skipToken), serviceCallback);
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @param skipToken the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRulesetList object
     */
    public Observable<ScanRulesetList> listAllAsync(String skipToken) {
        return listAllWithServiceResponseAsync(skipToken).map(new Func1<ServiceResponse<ScanRulesetList>, ScanRulesetList>() {
            @Override
            public ScanRulesetList call(ServiceResponse<ScanRulesetList> response) {
                return response.body();
            }
        });
    }

    /**
     * List scan rulesets in Data catalog.
     *
     * @param skipToken the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ScanRulesetList object
     */
    public Observable<ServiceResponse<ScanRulesetList>> listAllWithServiceResponseAsync(String skipToken) {
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        return service.listAll(skipToken, this.client.accountId(), this.client.accountName(), this.client.apiVersion())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ScanRulesetList>>>() {
                @Override
                public Observable<ServiceResponse<ScanRulesetList>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ScanRulesetList> clientResponse = listAllDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<ScanRulesetList> listAllDelegate(Response<ResponseBody> response) throws ErrorResponseModelException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<ScanRulesetList, ErrorResponseModelException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<ScanRulesetList>() { }.getType())
                .registerError(ErrorResponseModelException.class)
                .build(response);
    }

}
