/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AdlsGen1ScanRulesetProperties model.
 */
public class AdlsGen1ScanRulesetProperties extends ScanRulesetProperties {
    /**
     * The scanningRule property.
     */
    @JsonProperty(value = "scanningRule")
    private AdlsGen1ScanRulesetPropertiesScanningRule scanningRule;

    /**
     * Get the scanningRule value.
     *
     * @return the scanningRule value
     */
    public AdlsGen1ScanRulesetPropertiesScanningRule scanningRule() {
        return this.scanningRule;
    }

    /**
     * Set the scanningRule value.
     *
     * @param scanningRule the scanningRule value to set
     * @return the AdlsGen1ScanRulesetProperties object itself.
     */
    public AdlsGen1ScanRulesetProperties withScanningRule(AdlsGen1ScanRulesetPropertiesScanningRule scanningRule) {
        this.scanningRule = scanningRule;
        return this;
    }

}
