/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AdlsGen2AccessKeyScanProperties model.
 */
public class AdlsGen2AccessKeyScanProperties extends ScanProperties {
    /**
     * The accessKey property.
     */
    @JsonProperty(value = "accessKey")
    private String accessKey;

    /**
     * Get the accessKey value.
     *
     * @return the accessKey value
     */
    public String accessKey() {
        return this.accessKey;
    }

    /**
     * Set the accessKey value.
     *
     * @param accessKey the accessKey value to set
     * @return the AdlsGen2AccessKeyScanProperties object itself.
     */
    public AdlsGen2AccessKeyScanProperties withAccessKey(String accessKey) {
        this.accessKey = accessKey;
        return this;
    }

}
