/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AzureCosmosDbAccessKeyScanProperties model.
 */
public class AzureCosmosDbAccessKeyScanProperties extends ScanProperties {
    /**
     * The accessKey property.
     */
    @JsonProperty(value = "accessKey")
    private String accessKey;

    /**
     * The databaseName property.
     */
    @JsonProperty(value = "databaseName")
    private String databaseName;

    /**
     * Get the accessKey value.
     *
     * @return the accessKey value
     */
    public String accessKey() {
        return this.accessKey;
    }

    /**
     * Set the accessKey value.
     *
     * @param accessKey the accessKey value to set
     * @return the AzureCosmosDbAccessKeyScanProperties object itself.
     */
    public AzureCosmosDbAccessKeyScanProperties withAccessKey(String accessKey) {
        this.accessKey = accessKey;
        return this;
    }

    /**
     * Get the databaseName value.
     *
     * @return the databaseName value
     */
    public String databaseName() {
        return this.databaseName;
    }

    /**
     * Set the databaseName value.
     *
     * @param databaseName the databaseName value to set
     * @return the AzureCosmosDbAccessKeyScanProperties object itself.
     */
    public AzureCosmosDbAccessKeyScanProperties withDatabaseName(String databaseName) {
        this.databaseName = databaseName;
        return this;
    }

}
