/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AzureDataSourceProperties model.
 */
public class AzureDataSourceProperties extends DataSourceProperties {
    /**
     * The resourceGroup property.
     */
    @JsonProperty(value = "resourceGroup")
    private String resourceGroup;

    /**
     * The subscriptionId property.
     */
    @JsonProperty(value = "subscriptionId")
    private String subscriptionId;

    /**
     * Get the resourceGroup value.
     *
     * @return the resourceGroup value
     */
    public String resourceGroup() {
        return this.resourceGroup;
    }

    /**
     * Set the resourceGroup value.
     *
     * @param resourceGroup the resourceGroup value to set
     * @return the AzureDataSourceProperties object itself.
     */
    public AzureDataSourceProperties withResourceGroup(String resourceGroup) {
        this.resourceGroup = resourceGroup;
        return this;
    }

    /**
     * Get the subscriptionId value.
     *
     * @return the subscriptionId value
     */
    public String subscriptionId() {
        return this.subscriptionId;
    }

    /**
     * Set the subscriptionId value.
     *
     * @param subscriptionId the subscriptionId value to set
     * @return the AzureDataSourceProperties object itself.
     */
    public AzureDataSourceProperties withSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }

}
