/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * The AzureSqlDatabaseManagedInstanceServicePrincipalScan model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind", defaultImpl = AzureSqlDatabaseManagedInstanceServicePrincipalScan.class)
@JsonTypeName("AzureSqlDatabaseManagedInstanceServicePrincipal")
@JsonFlatten
public class AzureSqlDatabaseManagedInstanceServicePrincipalScan extends Scan {
    /**
     * The scanRulesetName property.
     */
    @JsonProperty(value = "properties.scanRulesetName")
    private String scanRulesetName;

    /**
     * The workers property.
     */
    @JsonProperty(value = "properties.workers")
    private Integer workers;

    /**
     * The createdAt property.
     */
    @JsonProperty(value = "properties.createdAt", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime createdAt;

    /**
     * The lastModifiedAt property.
     */
    @JsonProperty(value = "properties.lastModifiedAt", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime lastModifiedAt;

    /**
     * The serverEndpoint property.
     */
    @JsonProperty(value = "properties.serverEndpoint")
    private String serverEndpoint;

    /**
     * The databaseName property.
     */
    @JsonProperty(value = "properties.databaseName")
    private String databaseName;

    /**
     * The tenantId property.
     */
    @JsonProperty(value = "properties.tenantId")
    private String tenantId;

    /**
     * The servicePrincipalId property.
     */
    @JsonProperty(value = "properties.servicePrincipalId")
    private String servicePrincipalId;

    /**
     * The servicePrincipalKey property.
     */
    @JsonProperty(value = "properties.servicePrincipalKey")
    private String servicePrincipalKey;

    /**
     * Get the scanRulesetName value.
     *
     * @return the scanRulesetName value
     */
    public String scanRulesetName() {
        return this.scanRulesetName;
    }

    /**
     * Set the scanRulesetName value.
     *
     * @param scanRulesetName the scanRulesetName value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withScanRulesetName(String scanRulesetName) {
        this.scanRulesetName = scanRulesetName;
        return this;
    }

    /**
     * Get the workers value.
     *
     * @return the workers value
     */
    public Integer workers() {
        return this.workers;
    }

    /**
     * Set the workers value.
     *
     * @param workers the workers value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withWorkers(Integer workers) {
        this.workers = workers;
        return this;
    }

    /**
     * Get the createdAt value.
     *
     * @return the createdAt value
     */
    public DateTime createdAt() {
        return this.createdAt;
    }

    /**
     * Get the lastModifiedAt value.
     *
     * @return the lastModifiedAt value
     */
    public DateTime lastModifiedAt() {
        return this.lastModifiedAt;
    }

    /**
     * Get the serverEndpoint value.
     *
     * @return the serverEndpoint value
     */
    public String serverEndpoint() {
        return this.serverEndpoint;
    }

    /**
     * Set the serverEndpoint value.
     *
     * @param serverEndpoint the serverEndpoint value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withServerEndpoint(String serverEndpoint) {
        this.serverEndpoint = serverEndpoint;
        return this;
    }

    /**
     * Get the databaseName value.
     *
     * @return the databaseName value
     */
    public String databaseName() {
        return this.databaseName;
    }

    /**
     * Set the databaseName value.
     *
     * @param databaseName the databaseName value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withDatabaseName(String databaseName) {
        this.databaseName = databaseName;
        return this;
    }

    /**
     * Get the tenantId value.
     *
     * @return the tenantId value
     */
    public String tenantId() {
        return this.tenantId;
    }

    /**
     * Set the tenantId value.
     *
     * @param tenantId the tenantId value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withTenantId(String tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Get the servicePrincipalId value.
     *
     * @return the servicePrincipalId value
     */
    public String servicePrincipalId() {
        return this.servicePrincipalId;
    }

    /**
     * Set the servicePrincipalId value.
     *
     * @param servicePrincipalId the servicePrincipalId value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withServicePrincipalId(String servicePrincipalId) {
        this.servicePrincipalId = servicePrincipalId;
        return this;
    }

    /**
     * Get the servicePrincipalKey value.
     *
     * @return the servicePrincipalKey value
     */
    public String servicePrincipalKey() {
        return this.servicePrincipalKey;
    }

    /**
     * Set the servicePrincipalKey value.
     *
     * @param servicePrincipalKey the servicePrincipalKey value to set
     * @return the AzureSqlDatabaseManagedInstanceServicePrincipalScan object itself.
     */
    public AzureSqlDatabaseManagedInstanceServicePrincipalScan withServicePrincipalKey(String servicePrincipalKey) {
        this.servicePrincipalKey = servicePrincipalKey;
        return this;
    }

}
