/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;


/**
 * The AzureSqlDatabaseMsiScanProperties model.
 */
public class AzureSqlDatabaseMsiScanProperties extends AzureSqlScanProperties {
}
