/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AzureFileServiceAccessKeyScanProperties model.
 */
public class AzureFileServiceAccessKeyScanProperties extends ScanProperties {
    /**
     * The accessKey property.
     */
    @JsonProperty(value = "accessKey")
    private String accessKey;

    /**
     * The shareName property.
     */
    @JsonProperty(value = "shareName")
    private String shareName;

    /**
     * Get the accessKey value.
     *
     * @return the accessKey value
     */
    public String accessKey() {
        return this.accessKey;
    }

    /**
     * Set the accessKey value.
     *
     * @param accessKey the accessKey value to set
     * @return the AzureFileServiceAccessKeyScanProperties object itself.
     */
    public AzureFileServiceAccessKeyScanProperties withAccessKey(String accessKey) {
        this.accessKey = accessKey;
        return this;
    }

    /**
     * Get the shareName value.
     *
     * @return the shareName value
     */
    public String shareName() {
        return this.shareName;
    }

    /**
     * Set the shareName value.
     *
     * @param shareName the shareName value to set
     * @return the AzureFileServiceAccessKeyScanProperties object itself.
     */
    public AzureFileServiceAccessKeyScanProperties withShareName(String shareName) {
        this.shareName = shareName;
        return this;
    }

}
