/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The ClassificationRule model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind", defaultImpl = ClassificationRule.class)
@JsonTypeName("ClassificationRule")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "System", value = SystemClassificationRule.class),
    @JsonSubTypes.Type(name = "Custom", value = CustomClassificationRule.class)
})
public class ClassificationRule extends ProxyResource {
}
