/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.msft.babylonscanningservice.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ScanRunProperties model.
 */
public class ScanRunProperties {
    /**
     * Possible values include: 'Full', 'Incremental'.
     */
    @JsonProperty(value = "scanLevel")
    private String scanLevel;

    /**
     * The incrementalScanStartTime property.
     */
    @JsonProperty(value = "incrementalScanStartTime")
    private DateTime incrementalScanStartTime;

    /**
     * Get possible values include: 'Full', 'Incremental'.
     *
     * @return the scanLevel value
     */
    public String scanLevel() {
        return this.scanLevel;
    }

    /**
     * Set possible values include: 'Full', 'Incremental'.
     *
     * @param scanLevel the scanLevel value to set
     * @return the ScanRunProperties object itself.
     */
    public ScanRunProperties withScanLevel(String scanLevel) {
        this.scanLevel = scanLevel;
        return this;
    }

    /**
     * Get the incrementalScanStartTime value.
     *
     * @return the incrementalScanStartTime value
     */
    public DateTime incrementalScanStartTime() {
        return this.incrementalScanStartTime;
    }

    /**
     * Set the incrementalScanStartTime value.
     *
     * @param incrementalScanStartTime the incrementalScanStartTime value to set
     * @return the ScanRunProperties object itself.
     */
    public ScanRunProperties withIncrementalScanStartTime(DateTime incrementalScanStartTime) {
        this.incrementalScanStartTime = incrementalScanStartTime;
        return this;
    }

}
