/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import com.msft.atlasscanservice.implementation.JsonAtlasEntitiesWithExtInfoInner;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EntityCreateRequestV2.
 * The class for hook notification for type ENTITY_CREATE_V2.
 */
public class JsonEntityCreateRequestV2 {
    /**
     * The type of the notification. Different behavior will be invoked by the
     * value. Possible values include: 'TYPE_CREATE', 'TYPE_UPDATE',
     * 'ENTITY_CREATE', 'ENTITY_PARTIAL_UPDATE', 'ENTITY_FULL_UPDATE',
     * 'ENTITY_DELETE', 'ENTITY_CREATE_V2', 'ENTITY_PARTIAL_UPDATE_V2',
     * 'ENTITY_FULL_UPDATE_V2', 'ENTITY_DELETE_V2'.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * The user of the notification. Default to be "UNKNOWN".
     */
    @JsonProperty(value = "user")
    private String user;

    /**
     * The entities property.
     */
    @JsonProperty(value = "entities")
    private JsonAtlasEntitiesWithExtInfoInner entities;

    /**
     * Get the type of the notification. Different behavior will be invoked by the value. Possible values include: 'TYPE_CREATE', 'TYPE_UPDATE', 'ENTITY_CREATE', 'ENTITY_PARTIAL_UPDATE', 'ENTITY_FULL_UPDATE', 'ENTITY_DELETE', 'ENTITY_CREATE_V2', 'ENTITY_PARTIAL_UPDATE_V2', 'ENTITY_FULL_UPDATE_V2', 'ENTITY_DELETE_V2'.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type of the notification. Different behavior will be invoked by the value. Possible values include: 'TYPE_CREATE', 'TYPE_UPDATE', 'ENTITY_CREATE', 'ENTITY_PARTIAL_UPDATE', 'ENTITY_FULL_UPDATE', 'ENTITY_DELETE', 'ENTITY_CREATE_V2', 'ENTITY_PARTIAL_UPDATE_V2', 'ENTITY_FULL_UPDATE_V2', 'ENTITY_DELETE_V2'.
     *
     * @param type the type value to set
     * @return the JsonEntityCreateRequestV2 object itself.
     */
    public JsonEntityCreateRequestV2 withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the user of the notification. Default to be "UNKNOWN".
     *
     * @return the user value
     */
    public String user() {
        return this.user;
    }

    /**
     * Set the user of the notification. Default to be "UNKNOWN".
     *
     * @param user the user value to set
     * @return the JsonEntityCreateRequestV2 object itself.
     */
    public JsonEntityCreateRequestV2 withUser(String user) {
        this.user = user;
        return this;
    }

    /**
     * Get the entities value.
     *
     * @return the entities value
     */
    public JsonAtlasEntitiesWithExtInfoInner entities() {
        return this.entities;
    }

    /**
     * Set the entities value.
     *
     * @param entities the entities value to set
     * @return the JsonEntityCreateRequestV2 object itself.
     */
    public JsonEntityCreateRequestV2 withEntities(JsonAtlasEntitiesWithExtInfoInner entities) {
        this.entities = entities;
        return this;
    }

}
