/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LineageRelation.
 * The lineage relation with GUID of the from and to entity.
 */
public class JsonLineageRelation {
    /**
     * The GUID of from-entity.
     */
    @JsonProperty(value = "fromEntityId")
    private String fromEntityId;

    /**
     * The GUID of relationship.
     */
    @JsonProperty(value = "relationshipId")
    private String relationshipId;

    /**
     * The GUID of to-entity.
     */
    @JsonProperty(value = "toEntityId")
    private String toEntityId;

    /**
     * Get the GUID of from-entity.
     *
     * @return the fromEntityId value
     */
    public String fromEntityId() {
        return this.fromEntityId;
    }

    /**
     * Set the GUID of from-entity.
     *
     * @param fromEntityId the fromEntityId value to set
     * @return the JsonLineageRelation object itself.
     */
    public JsonLineageRelation withFromEntityId(String fromEntityId) {
        this.fromEntityId = fromEntityId;
        return this;
    }

    /**
     * Get the GUID of relationship.
     *
     * @return the relationshipId value
     */
    public String relationshipId() {
        return this.relationshipId;
    }

    /**
     * Set the GUID of relationship.
     *
     * @param relationshipId the relationshipId value to set
     * @return the JsonLineageRelation object itself.
     */
    public JsonLineageRelation withRelationshipId(String relationshipId) {
        this.relationshipId = relationshipId;
        return this;
    }

    /**
     * Get the GUID of to-entity.
     *
     * @return the toEntityId value
     */
    public String toEntityId() {
        return this.toEntityId;
    }

    /**
     * Set the GUID of to-entity.
     *
     * @param toEntityId the toEntityId value to set
     * @return the JsonLineageRelation object itself.
     */
    public JsonLineageRelation withToEntityId(String toEntityId) {
        this.toEntityId = toEntityId;
        return this;
    }

}
