/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FilterCriteria.
 * The filter criteria with attributes and condition.
 */
public class JsonFilterCriteria {
    /**
     * The name of the attribute.
     */
    @JsonProperty(value = "attributeName")
    private String attributeName;

    /**
     * The value of the attribute.
     */
    @JsonProperty(value = "attributeValue")
    private String attributeValue;

    /**
     * Possible values include: 'AND', 'OR'.
     */
    @JsonProperty(value = "condition")
    private String condition;

    /**
     * An array of filter criteria.
     */
    @JsonProperty(value = "criterion")
    private List<JsonFilterCriteria> criterion;

    /**
     * Possible values include: 'LT', 'GT', 'LTE', 'GTE', 'EQ', 'NEQ', 'IN',
     * 'LIKE', 'STARTS_WITH', 'ENDS_WITH', 'CONTAINS', 'CONTAINS_ANY',
     * 'CONTAINS_ALL', 'IS_NULL', 'NOT_NULL'.
     */
    @JsonProperty(value = "operator")
    private String operator;

    /**
     * Get the name of the attribute.
     *
     * @return the attributeName value
     */
    public String attributeName() {
        return this.attributeName;
    }

    /**
     * Set the name of the attribute.
     *
     * @param attributeName the attributeName value to set
     * @return the JsonFilterCriteria object itself.
     */
    public JsonFilterCriteria withAttributeName(String attributeName) {
        this.attributeName = attributeName;
        return this;
    }

    /**
     * Get the value of the attribute.
     *
     * @return the attributeValue value
     */
    public String attributeValue() {
        return this.attributeValue;
    }

    /**
     * Set the value of the attribute.
     *
     * @param attributeValue the attributeValue value to set
     * @return the JsonFilterCriteria object itself.
     */
    public JsonFilterCriteria withAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
        return this;
    }

    /**
     * Get possible values include: 'AND', 'OR'.
     *
     * @return the condition value
     */
    public String condition() {
        return this.condition;
    }

    /**
     * Set possible values include: 'AND', 'OR'.
     *
     * @param condition the condition value to set
     * @return the JsonFilterCriteria object itself.
     */
    public JsonFilterCriteria withCondition(String condition) {
        this.condition = condition;
        return this;
    }

    /**
     * Get an array of filter criteria.
     *
     * @return the criterion value
     */
    public List<JsonFilterCriteria> criterion() {
        return this.criterion;
    }

    /**
     * Set an array of filter criteria.
     *
     * @param criterion the criterion value to set
     * @return the JsonFilterCriteria object itself.
     */
    public JsonFilterCriteria withCriterion(List<JsonFilterCriteria> criterion) {
        this.criterion = criterion;
        return this;
    }

    /**
     * Get possible values include: 'LT', 'GT', 'LTE', 'GTE', 'EQ', 'NEQ', 'IN', 'LIKE', 'STARTS_WITH', 'ENDS_WITH', 'CONTAINS', 'CONTAINS_ANY', 'CONTAINS_ALL', 'IS_NULL', 'NOT_NULL'.
     *
     * @return the operator value
     */
    public String operator() {
        return this.operator;
    }

    /**
     * Set possible values include: 'LT', 'GT', 'LTE', 'GTE', 'EQ', 'NEQ', 'IN', 'LIKE', 'STARTS_WITH', 'ENDS_WITH', 'CONTAINS', 'CONTAINS_ANY', 'CONTAINS_ALL', 'IS_NULL', 'NOT_NULL'.
     *
     * @param operator the operator value to set
     * @return the JsonFilterCriteria object itself.
     */
    public JsonFilterCriteria withOperator(String operator) {
        this.operator = operator;
        return this;
    }

}
