/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SearchResultValue.
 * The result item of the search.
 */
public class JsonSearchResultValue {
    /**
     * A highlight list that consists of index fields id ,qualifiedName, name,
     * description, typeName, and owner. When the keyword appears in those
     * fields, the value of the field, attached with emphasis mark, is returned
     * as an element of @search.highlights list.
     */
    @JsonProperty(value = "@search\\.highlights")
    private List<JsonSearchHighlights> searchhighlights;

    /**
     * The search score calculated by Azure Search. The results are ordered by
     * search score by default..
     */
    @JsonProperty(value = "@search\\.score")
    private Double searchscore;

    /**
     * The description of the record.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The ID of the record.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The name of the record.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The owner of the record.
     */
    @JsonProperty(value = "owner")
    private String owner;

    /**
     * The qualified name of the record.
     */
    @JsonProperty(value = "qualifiedName")
    private String qualifiedName;

    /**
     * The type name of the record.
     */
    @JsonProperty(value = "typeName")
    private String typeName;

    /**
     * Get a highlight list that consists of index fields id ,qualifiedName, name, description, typeName, and owner. When the keyword appears in those fields, the value of the field, attached with emphasis mark, is returned as an element of @search.highlights list.
     *
     * @return the searchhighlights value
     */
    public List<JsonSearchHighlights> searchhighlights() {
        return this.searchhighlights;
    }

    /**
     * Set a highlight list that consists of index fields id ,qualifiedName, name, description, typeName, and owner. When the keyword appears in those fields, the value of the field, attached with emphasis mark, is returned as an element of @search.highlights list.
     *
     * @param searchhighlights the searchhighlights value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withSearchhighlights(List<JsonSearchHighlights> searchhighlights) {
        this.searchhighlights = searchhighlights;
        return this;
    }

    /**
     * Get the search score calculated by Azure Search. The results are ordered by search score by default..
     *
     * @return the searchscore value
     */
    public Double searchscore() {
        return this.searchscore;
    }

    /**
     * Set the search score calculated by Azure Search. The results are ordered by search score by default..
     *
     * @param searchscore the searchscore value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withSearchscore(Double searchscore) {
        this.searchscore = searchscore;
        return this;
    }

    /**
     * Get the description of the record.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description of the record.
     *
     * @param description the description value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the ID of the record.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the ID of the record.
     *
     * @param id the id value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name of the record.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of the record.
     *
     * @param name the name value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the owner of the record.
     *
     * @return the owner value
     */
    public String owner() {
        return this.owner;
    }

    /**
     * Set the owner of the record.
     *
     * @param owner the owner value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withOwner(String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get the qualified name of the record.
     *
     * @return the qualifiedName value
     */
    public String qualifiedName() {
        return this.qualifiedName;
    }

    /**
     * Set the qualified name of the record.
     *
     * @param qualifiedName the qualifiedName value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withQualifiedName(String qualifiedName) {
        this.qualifiedName = qualifiedName;
        return this;
    }

    /**
     * Get the type name of the record.
     *
     * @return the typeName value
     */
    public String typeName() {
        return this.typeName;
    }

    /**
     * Set the type name of the record.
     *
     * @param typeName the typeName value to set
     * @return the JsonSearchResultValue object itself.
     */
    public JsonSearchResultValue withTypeName(String typeName) {
        this.typeName = typeName;
        return this;
    }

}
