/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasRelationshipEndDef.
 * The relationshipEndDef represents an end of the relationship. The end of the
 * relationship is defined by a type, an
 * attribute name, cardinality and whether it  is the container end of the
 * relationship.
 */
public class JsonAtlasRelationshipEndDef {
    /**
     * Possible values include: 'SINGLE', 'LIST', 'SET'.
     */
    @JsonProperty(value = "cardinality")
    private String cardinality;

    /**
     * The description of the relationship end definition.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Determines if it is container.
     */
    @JsonProperty(value = "isContainer")
    private Boolean isContainer;

    /**
     * Determines if it is a legacy attribute.
     */
    @JsonProperty(value = "isLegacyAttribute")
    private Boolean isLegacyAttribute;

    /**
     * The name of the relationship end definition.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The type of the relationship end.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Get possible values include: 'SINGLE', 'LIST', 'SET'.
     *
     * @return the cardinality value
     */
    public String cardinality() {
        return this.cardinality;
    }

    /**
     * Set possible values include: 'SINGLE', 'LIST', 'SET'.
     *
     * @param cardinality the cardinality value to set
     * @return the JsonAtlasRelationshipEndDef object itself.
     */
    public JsonAtlasRelationshipEndDef withCardinality(String cardinality) {
        this.cardinality = cardinality;
        return this;
    }

    /**
     * Get the description of the relationship end definition.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description of the relationship end definition.
     *
     * @param description the description value to set
     * @return the JsonAtlasRelationshipEndDef object itself.
     */
    public JsonAtlasRelationshipEndDef withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get determines if it is container.
     *
     * @return the isContainer value
     */
    public Boolean isContainer() {
        return this.isContainer;
    }

    /**
     * Set determines if it is container.
     *
     * @param isContainer the isContainer value to set
     * @return the JsonAtlasRelationshipEndDef object itself.
     */
    public JsonAtlasRelationshipEndDef withIsContainer(Boolean isContainer) {
        this.isContainer = isContainer;
        return this;
    }

    /**
     * Get determines if it is a legacy attribute.
     *
     * @return the isLegacyAttribute value
     */
    public Boolean isLegacyAttribute() {
        return this.isLegacyAttribute;
    }

    /**
     * Set determines if it is a legacy attribute.
     *
     * @param isLegacyAttribute the isLegacyAttribute value to set
     * @return the JsonAtlasRelationshipEndDef object itself.
     */
    public JsonAtlasRelationshipEndDef withIsLegacyAttribute(Boolean isLegacyAttribute) {
        this.isLegacyAttribute = isLegacyAttribute;
        return this;
    }

    /**
     * Get the name of the relationship end definition.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of the relationship end definition.
     *
     * @param name the name value to set
     * @return the JsonAtlasRelationshipEndDef object itself.
     */
    public JsonAtlasRelationshipEndDef withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the type of the relationship end.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type of the relationship end.
     *
     * @param type the type value to set
     * @return the JsonAtlasRelationshipEndDef object itself.
     */
    public JsonAtlasRelationshipEndDef withType(String type) {
        this.type = type;
        return this;
    }

}
