/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasStruct.
 * Captures details of struct contents. Not instantiated directly, used only
 * via AtlasEntity, AtlasClassification.
 */
public class JsonAtlasStruct {
    /**
     * The attributes of the struct.
     */
    @JsonProperty(value = "attributes")
    private Map<String, Object> attributes;

    /**
     * The name of the type.
     */
    @JsonProperty(value = "typeName")
    private String typeName;

    /**
     * Get the attributes of the struct.
     *
     * @return the attributes value
     */
    public Map<String, Object> attributes() {
        return this.attributes;
    }

    /**
     * Set the attributes of the struct.
     *
     * @param attributes the attributes value to set
     * @return the JsonAtlasStruct object itself.
     */
    public JsonAtlasStruct withAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
        return this;
    }

    /**
     * Get the name of the type.
     *
     * @return the typeName value
     */
    public String typeName() {
        return this.typeName;
    }

    /**
     * Set the name of the type.
     *
     * @param typeName the typeName value to set
     * @return the JsonAtlasStruct object itself.
     */
    public JsonAtlasStruct withTypeName(String typeName) {
        this.typeName = typeName;
        return this;
    }

}
