/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DataScanPermissionCheckRequest.
 * Request for data scan permission check.
 */
public class JsonDataScanPermissionCheckRequest {
    /**
     * Name of the catalog.
     */
    @JsonProperty(value = "catalogName")
    private String catalogName;

    /**
     * User ID of the catalog.
     */
    @JsonProperty(value = "userId")
    private String userId;

    /**
     * Get name of the catalog.
     *
     * @return the catalogName value
     */
    public String catalogName() {
        return this.catalogName;
    }

    /**
     * Set name of the catalog.
     *
     * @param catalogName the catalogName value to set
     * @return the JsonDataScanPermissionCheckRequest object itself.
     */
    public JsonDataScanPermissionCheckRequest withCatalogName(String catalogName) {
        this.catalogName = catalogName;
        return this;
    }

    /**
     * Get user ID of the catalog.
     *
     * @return the userId value
     */
    public String userId() {
        return this.userId;
    }

    /**
     * Set user ID of the catalog.
     *
     * @param userId the userId value to set
     * @return the JsonDataScanPermissionCheckRequest object itself.
     */
    public JsonDataScanPermissionCheckRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }

}
