/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import java.util.List;
import com.msft.atlasscanservice.implementation.JsonAtlasClassificationInner;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasGlossaryBaseObject.
 * The glossary base object.
 */
public class JsonAtlasGlossaryBaseObject extends JsonAtlasBaseModelObject {
    /**
     * An array of classifications.
     */
    @JsonProperty(value = "classifications")
    private List<JsonAtlasClassificationInner> classifications;

    /**
     * The long version description.
     */
    @JsonProperty(value = "longDescription")
    private String longDescription;

    /**
     * The name of the glossary object.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The qualified name of the glossary object.
     */
    @JsonProperty(value = "qualifiedName")
    private String qualifiedName;

    /**
     * The short version of description.
     */
    @JsonProperty(value = "shortDescription")
    private String shortDescription;

    /**
     * Get an array of classifications.
     *
     * @return the classifications value
     */
    public List<JsonAtlasClassificationInner> classifications() {
        return this.classifications;
    }

    /**
     * Set an array of classifications.
     *
     * @param classifications the classifications value to set
     * @return the JsonAtlasGlossaryBaseObject object itself.
     */
    public JsonAtlasGlossaryBaseObject withClassifications(List<JsonAtlasClassificationInner> classifications) {
        this.classifications = classifications;
        return this;
    }

    /**
     * Get the long version description.
     *
     * @return the longDescription value
     */
    public String longDescription() {
        return this.longDescription;
    }

    /**
     * Set the long version description.
     *
     * @param longDescription the longDescription value to set
     * @return the JsonAtlasGlossaryBaseObject object itself.
     */
    public JsonAtlasGlossaryBaseObject withLongDescription(String longDescription) {
        this.longDescription = longDescription;
        return this;
    }

    /**
     * Get the name of the glossary object.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of the glossary object.
     *
     * @param name the name value to set
     * @return the JsonAtlasGlossaryBaseObject object itself.
     */
    public JsonAtlasGlossaryBaseObject withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the qualified name of the glossary object.
     *
     * @return the qualifiedName value
     */
    public String qualifiedName() {
        return this.qualifiedName;
    }

    /**
     * Set the qualified name of the glossary object.
     *
     * @param qualifiedName the qualifiedName value to set
     * @return the JsonAtlasGlossaryBaseObject object itself.
     */
    public JsonAtlasGlossaryBaseObject withQualifiedName(String qualifiedName) {
        this.qualifiedName = qualifiedName;
        return this;
    }

    /**
     * Get the short version of description.
     *
     * @return the shortDescription value
     */
    public String shortDescription() {
        return this.shortDescription;
    }

    /**
     * Set the short version of description.
     *
     * @param shortDescription the shortDescription value to set
     * @return the JsonAtlasGlossaryBaseObject object itself.
     */
    public JsonAtlasGlossaryBaseObject withShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
        return this;
    }

}
