/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasUserSavedSearch.
 * User saved search.
 */
public class JsonAtlasUserSavedSearch extends JsonAtlasBaseModelObject {
    /**
     * The name of the saved search.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The owner name of the saved search.
     */
    @JsonProperty(value = "ownerName")
    private String ownerName;

    /**
     * The searchParameters property.
     */
    @JsonProperty(value = "searchParameters")
    private JsonSearchParameters searchParameters;

    /**
     * Possible values include: 'BASIC', 'ADVANCED'.
     */
    @JsonProperty(value = "searchType")
    private String searchType;

    /**
     * The UI parameters.
     */
    @JsonProperty(value = "uiParameters")
    private String uiParameters;

    /**
     * Get the name of the saved search.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of the saved search.
     *
     * @param name the name value to set
     * @return the JsonAtlasUserSavedSearch object itself.
     */
    public JsonAtlasUserSavedSearch withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the owner name of the saved search.
     *
     * @return the ownerName value
     */
    public String ownerName() {
        return this.ownerName;
    }

    /**
     * Set the owner name of the saved search.
     *
     * @param ownerName the ownerName value to set
     * @return the JsonAtlasUserSavedSearch object itself.
     */
    public JsonAtlasUserSavedSearch withOwnerName(String ownerName) {
        this.ownerName = ownerName;
        return this;
    }

    /**
     * Get the searchParameters value.
     *
     * @return the searchParameters value
     */
    public JsonSearchParameters searchParameters() {
        return this.searchParameters;
    }

    /**
     * Set the searchParameters value.
     *
     * @param searchParameters the searchParameters value to set
     * @return the JsonAtlasUserSavedSearch object itself.
     */
    public JsonAtlasUserSavedSearch withSearchParameters(JsonSearchParameters searchParameters) {
        this.searchParameters = searchParameters;
        return this;
    }

    /**
     * Get possible values include: 'BASIC', 'ADVANCED'.
     *
     * @return the searchType value
     */
    public String searchType() {
        return this.searchType;
    }

    /**
     * Set possible values include: 'BASIC', 'ADVANCED'.
     *
     * @param searchType the searchType value to set
     * @return the JsonAtlasUserSavedSearch object itself.
     */
    public JsonAtlasUserSavedSearch withSearchType(String searchType) {
        this.searchType = searchType;
        return this;
    }

    /**
     * Get the UI parameters.
     *
     * @return the uiParameters value
     */
    public String uiParameters() {
        return this.uiParameters;
    }

    /**
     * Set the UI parameters.
     *
     * @param uiParameters the uiParameters value to set
     * @return the JsonAtlasUserSavedSearch object itself.
     */
    public JsonAtlasUserSavedSearch withUiParameters(String uiParameters) {
        this.uiParameters = uiParameters;
        return this;
    }

}
