/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.msft.atlasscanservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AtlasTermCategorizationHeader.
 * The basic information for term categorization.
 */
public class JsonAtlasTermCategorizationHeader {
    /**
     * The GUID of the category.
     */
    @JsonProperty(value = "categoryGuid")
    private String categoryGuid;

    /**
     * The description of the record.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The display text.
     */
    @JsonProperty(value = "displayText")
    private String displayText;

    /**
     * The GUID of the relationship.
     */
    @JsonProperty(value = "relationGuid")
    private String relationGuid;

    /**
     * Possible values include: 'DRAFT', 'ACTIVE', 'DEPRECATED', 'OBSOLETE',
     * 'OTHER'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * Get the GUID of the category.
     *
     * @return the categoryGuid value
     */
    public String categoryGuid() {
        return this.categoryGuid;
    }

    /**
     * Set the GUID of the category.
     *
     * @param categoryGuid the categoryGuid value to set
     * @return the JsonAtlasTermCategorizationHeader object itself.
     */
    public JsonAtlasTermCategorizationHeader withCategoryGuid(String categoryGuid) {
        this.categoryGuid = categoryGuid;
        return this;
    }

    /**
     * Get the description of the record.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description of the record.
     *
     * @param description the description value to set
     * @return the JsonAtlasTermCategorizationHeader object itself.
     */
    public JsonAtlasTermCategorizationHeader withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the display text.
     *
     * @return the displayText value
     */
    public String displayText() {
        return this.displayText;
    }

    /**
     * Set the display text.
     *
     * @param displayText the displayText value to set
     * @return the JsonAtlasTermCategorizationHeader object itself.
     */
    public JsonAtlasTermCategorizationHeader withDisplayText(String displayText) {
        this.displayText = displayText;
        return this;
    }

    /**
     * Get the GUID of the relationship.
     *
     * @return the relationGuid value
     */
    public String relationGuid() {
        return this.relationGuid;
    }

    /**
     * Set the GUID of the relationship.
     *
     * @param relationGuid the relationGuid value to set
     * @return the JsonAtlasTermCategorizationHeader object itself.
     */
    public JsonAtlasTermCategorizationHeader withRelationGuid(String relationGuid) {
        this.relationGuid = relationGuid;
        return this;
    }

    /**
     * Get possible values include: 'DRAFT', 'ACTIVE', 'DEPRECATED', 'OBSOLETE', 'OTHER'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set possible values include: 'DRAFT', 'ACTIVE', 'DEPRECATED', 'OBSOLETE', 'OTHER'.
     *
     * @param status the status value to set
     * @return the JsonAtlasTermCategorizationHeader object itself.
     */
    public JsonAtlasTermCategorizationHeader withStatus(String status) {
        this.status = status;
        return this;
    }

}
